# Patch 12e v2: Docs (save as UTF-8 with BOM)
$ErrorActionPreference = "Stop"
$ProjectRoot = "E:\InevioNet"
$DocsDir = Join-Path $ProjectRoot "docs"
New-Item -ItemType Directory -Path $DocsDir -Force | Out-Null

$arch = @(
    "# InevioNet — Архитектура",
    "",
    "## Философия",
    "",
    "Сети видят выбор, но выбора нет. Пакет всегда доставляется.",
    "",
    "InevioNet — децентрализованная самоэволюционирующая P2P-сеть,",
    "построенная по биомиметической модели: ДНК → Мицелий → P2P.",
    "",
    "## Три уровня",
    "",
    "### 1. ДНК (генотип)",
    "",
    "Файл: inevionet/evolution/genome.py",
    "",
    "Каждый узел имеет геном — набор из 14+ генов:",
    "",
    "- speed (0.0-1.0)",
    "- reliability (0.0-1.0)",
    "- stealth (0.0-1.0)",
    "- efficiency (0.0-1.0)",
    "- adaptability (0.0-1.0)",
    "- packet_size (64-9000)",
    "- ttl (1-64)",
    "- priority (1-10)",
    "- clone_threshold (1-10)",
    "- penetration_strategy (enum)",
    "- masking_channel (enum)",
    "- industrial_protocol (enum)",
    "- stego_method (enum)",
    "- use_polymorphic (bool)",
    "- use_ambient (bool)",
    "- use_stego (bool)",
    "",
    "### 2. Мицелий (фенотип)",
    "",
    "Файлы: inevionet/mycelium/*.py",
    "",
    "- engine.py — главный движок",
    "- penetration.py — проникновение (6 методов)",
    "- spores.py — автономные агенты",
    "- pheromones.py — маршрутизация по феромонам",
    "",
    "### 3. P2P-сеть (экосистема)",
    "",
    "Узлы 8 типов:",
    "",
    "- self — твой узел (зелёный)",
    "- wifi — Wi-Fi сети (синий)",
    "- super — супер-узлы (белый)",
    "- spore — споры мицелия (розовый)",
    "- ble — Bluetooth LE (голубой)",
    "- bluetooth — BT classic (синий)",
    "- cellular — LTE/5G (жёлтый)",
    "- industrial — Modbus/MQTT (оранжевый)",
    "- peer — другие узлы (фиолетовый)",
    "",
    "## Поток данных",
    "",
    "send -> encrypt -> sign -> transport",
    "  -> Tor (анонимно)",
    "  -> I2P (анонимно, РФ)",
    "  -> P2P Bridge (WebRTC)",
    "  -> Masking (DPI bypass)",
    "  -> Steganography (4 канала)",
    "  -> Direct (TCP/UDP/DNS/ICMP)",
    "",
    "receive <- verify <- decrypt <- decode",
    "",
    "## Эволюция",
    "",
    "Каждые 4 секунды: сканер обновляет узлы",
    "Каждые 40 секунд: evolve() — новое поколение",
    "Каждые 50 поколений: КАТАСТРОФА — сброс diversity",
    "",
    "### Fitness",
    "",
    "f(g) = speed*0.25 + reliability*0.30 + stealth*0.20",
    "     + efficiency*0.15 + adaptability*0.10 + bonus",
    "",
    "### Reward",
    "",
    "Успешная отправка: +0.1 к fitness",
    "Неудачная: -0.05 к fitness",
    "",
    "## Модули",
    "",
    "core       — 9 файлов, ядро (crypto, packet, logger)",
    "network    — 16 файлов, транспорты (TCP/UDP/DNS/ICMP/WS/WebRTC)",
    "mycelium   — 4 файла, мицелий (penetration, spores, pheromones)",
    "evolution  — 2 файла, генетический алгоритм",
    "masking    — 9 файлов, DPI bypass",
    "steganography — 5 файлов, скрытые каналы",
    "industrial — 5 файлов, Modbus/MQTT/OPCUA/DNP3",
    "identity   — 7 файлов, идентификация",
    "mesh       — 1 файл, авто-топология",
    "symbiotic  — 2 файла, экосистема",
    "ai         — 2 файла, selector + recursion",
    "web        — 2 файла, Flask + UI",
    "",
    "ВСЕГО: ~63 файла, ~22000 строк",
    "",
    "## Ссылки",
    "",
    "- docs/MODULES.md — детали модулей",
    "- docs/MATH.md — формальная математика",
    "- README_FOR_DUMMIES.md — инструкция"
)

[System.IO.File]::WriteAllLines((Join-Path $DocsDir "ARCHITECTURE.md"), $arch, [System.Text.UTF8Encoding]::new($false))
Write-Host "[OK] ARCHITECTURE.md" -ForegroundColor Green

$modules = @(
    "# InevioNet — Модули",
    "",
    "## core/",
    "",
    "- crypto.py — InevioCrypto, AES + RSA",
    "- packet.py — GDPPacket",
    "- logger.py — Логирование",
    "- constants.py — DataPaths, режимы",
    "- exceptions.py — Исключения",
    "- cache.py — LRU-кэш",
    "- beacon.py — Multicast beacons",
    "- async_utils.py — Асинхронность",
    "- stats_aggregator.py — Статистика",
    "",
    "## network/",
    "",
    "- tcp.py — TCPClient, TCPServer",
    "- udp.py — UDPClient, UDPHolePuncher, STUN",
    "- dns.py — DNSClient (QNAME/TXT)",
    "- http.py — HTTPClient (headers)",
    "- icmp.py — ICMPClient (raw socket)",
    "- websocket.py — WSClient",
    "- transport.py — UniversalTransport",
    "- rf_scanner.py — WiFi + BT + BLE + LTE + GPS",
    "- ble_scanner.py — BLE через bleak",
    "- lte_scanner.py — LTE через netsh mbn",
    "- cellular_scanner.py — Оператор + геолокация",
    "- tor_transport.py — SOCKS5 через Tor",
    "- i2p_transport.py — SAM bridge",
    "- webrtc_bridge.py — WebRTC DataChannel",
    "- bridge_broker.py — Координатор relay",
    "- relay_node.py — Узел-релей",
    "",
    "## mycelium/",
    "",
    "- engine.py — MyceliumEngine",
    "- penetration.py — 6 методов проникновения",
    "- spores.py — SporeManager, Spore",
    "- pheromones.py — PheromoneEngine",
    "",
    "## evolution/",
    "",
    "- genome.py — ProtocolGenome, 14 генов",
    "- engine.py — EvolutionEngine, catastrophe, reward",
    "",
    "## masking/",
    "",
    "- masking_engine.py — Главный движок",
    "- polymorphic.py — Фрагментация",
    "- ambient.py — Адаптация к трафику",
    "- bayesian.py — Байесовский выбор",
    "- channel_selector.py — Селектор каналов",
    "- firewall_model.py — Модель firewall",
    "- detection.py — KL-дивергенция",
    "- vulnerability_map.py — Карта уязвимостей",
    "- probing.py — Зондирование",
    "",
    "## steganography/",
    "",
    "- engine.py — SteganographyEngine",
    "- dns_tunnel.py — DNS-туннель",
    "- http_headers.py — HTTP-заголовки",
    "- icmp_payload.py — ICMP-payload",
    "- timing.py — Timing channel",
    "",
    "## industrial/",
    "",
    "- base.py — IndustrialProtocol",
    "- modbus.py — ModbusTCP, ModbusRTU",
    "- mqtt.py — MQTTClient",
    "- opcua.py — OPCUA",
    "- dnp3.py — DNP3",
    "",
    "## identity/",
    "",
    "- device_id.py — DeviceID",
    "- identity.py — DeviceIdentity",
    "- registry.py — DeviceRegistry",
    "- discovery.py — DiscoveryEngine",
    "- trust.py — TrustEngine",
    "- presence.py — PresenceManager",
    "- fingerprint.py — DeviceFingerprint",
    "",
    "## Остальные",
    "",
    "- mesh/auto_topology.py — Авто-топология",
    "- symbiotic/ecosystem.py — Экосистема",
    "- ai/selector.py — ProtocolSelector",
    "- ai/recursion.py — WeightedRecursion",
    "- web/app.py — Flask API",
    "- web/templates/index.html — iOS 27 UI",
    "- orchestrator.py — Главный класс"
)

[System.IO.File]::WriteAllLines((Join-Path $DocsDir "MODULES.md"), $modules, [System.Text.UTF8Encoding]::new($false))
Write-Host "[OK] MODULES.md" -ForegroundColor Green

$math = @(
    "# InevioNet — Формальная математика",
    "",
    "## 1. Ложный выбор — Мицелий",
    "",
    "Психология: пиво, вино или водка — иллюзия выбора.",
    "",
    "Формализация:",
    "A = {a1, ..., an} — множество альтернатив",
    "f: A -> R        — функция исходов",
    "f(ai) = r        — все ведут к одному",
    "",
    "Ложный выбор: |A| > 1 и |f(A)| = 1",
    "Мицелий: растёт во все стороны -> |f(A)| >> 1",
    "",
    "## 2. Геном как вектор",
    "",
    "g = (g1, ..., gn) in [0,1]^5 x Z^4 x E^k",
    "",
    "5 float генов: speed, reliability, stealth, efficiency, adaptability",
    "4 int гена: packet_size, ttl, priority, clone_threshold",
    "k enum генов: penetration, masking, industrial, stego",
    "",
    "## 3. Fitness функция",
    "",
    "f(g) = sum_i w_i * g_i + bonus(g)",
    "",
    "где w = (0.25, 0.30, 0.20, 0.15, 0.10)",
    "",
    "Bonus:",
    "size_bonus = max(0, 1 - abs(packet_size - 1400)/1400) * 0.05",
    "ttl_bonus = min(1, ttl/40) * 0.03",
    "priority_bonus = max(0, 1 - abs(priority-7)/10) * 0.02",
    "",
    "## 4. Эволюция",
    "",
    "Турнирный отбор:",
    "P_select(gi) = P(gi in tournament_size)",
    "winner = argmax_{g in T} f(g)",
    "",
    "Мутация:",
    "g'_i = g_i + N(0, sigma^2) с вероятностью p_m",
    "",
    "Кроссовер:",
    "child_i = alpha * parent1_i + (1-alpha) * parent2_i + N(0, 0.05)",
    "",
    "## 5. Diversity",
    "",
    "D = (1/n) * sum_i sigma_i",
    "",
    "где sigma_i — стандартное отклонение гена i.",
    "",
    "Проблема: D -> 0 при сходимости.",
    "Решение: КАТАСТРОФА каждые 50 поколений:",
    "1. Оставить 70% лучших",
    "2. Инжектировать 30% случайных геномов",
    "3. D растёт обратно",
    "",
    "## 6. Reward",
    "",
    "f(g, strategy) += +0.1  если success",
    "f(g, strategy) += -0.05 если failure",
    "",
    "## 7. Мицелий",
    "",
    "Апикальный рост:",
    "x_{t+1} = x_t + Delta * (cos theta_t, sin theta_t)",
    "theta_{t+1} = theta_t + N(0, sigma^2)",
    "",
    "Ветвление: процесс Гальтона-Ватсона:",
    "E[N(t)] = N_0 * mu^t",
    "",
    "Анастомозы: цикломатическая сложность:",
    "C = E - V + 1",
    "",
    "## 8. Феромоны",
    "",
    "Испарение:",
    "s(t) = s_0 * exp(-lambda * t / 60)",
    "",
    "Усиление:",
    "s = min(1, s + 0.1)",
    "",
    "Оценка:",
    "score = strength * success_rate",
    "",
    "## 9. Споры",
    "",
    "Жизнеспособность:",
    "v(t) = v_0 - 0.05 * t",
    "",
    "Условие выживания:",
    "N_s * p > 1",
    "",
    "## 10. Маскировка",
    "",
    "KL-дивергенция:",
    "D_KL(P || Q) = sum P(i) * log(P(i) / Q(i))",
    "",
    "Байесовский выбор:",
    "P(channel) = alpha / (alpha + beta)",
    "",
    "## 11. P2P Bridge",
    "",
    "Broker:",
    "relay* = argmin_{r in Relays} load_ratio(r)",
    "load_ratio(r) = current_load(r) / capacity(r)",
    "",
    "WebRTC:",
    "Offer: SDP_A -> Broker -> SDP_B (Answer)",
    "DataChannel: шифрование DTLS + SRTP",
    "",
    "## 12. Итог",
    "",
    "InevioNet = ДНК (геном) + Мицелий (сеть) + P2P (экосистема)",
    "",
    "Все три уровня подчиняются законам эволюции:",
    "- Мутация + отбор = адаптация",
    "- Катастрофа = punctuated equilibrium",
    "- Diversity = гарантия выживания"
)

[System.IO.File]::WriteAllLines((Join-Path $DocsDir "MATH.md"), $math, [System.Text.UTF8Encoding]::new($false))
Write-Host "[OK] MATH.md" -ForegroundColor Green

Write-Host ""
Write-Host "=== DOCS CREATED ===" -ForegroundColor Cyan
Get-ChildItem $DocsDir | ForEach-Object {
    Write-Host "  $($_.Name) ($([math]::Round($_.Length/1KB, 1)) KB)" -ForegroundColor White
}