# Patch 12e: Documentation
$ErrorActionPreference = "Stop"
$ProjectRoot = "E:\InevioNet"
$DocsDir = Join-Path $ProjectRoot "docs"
New-Item -ItemType Directory -Path $DocsDir -Force | Out-Null

# === ARCHITECTURE.md ===
$arch = @(
    "# InevioNet — Архитектура",
    "",
    "## Философия",
    "",
    "> Сети видят выбор, но выбора нет. Пакет всегда доставляется.",
    "",
    "InevioNet — децентрализованная самоэволюционирующая P2P-сеть,",
    "построенная по биомиметической модели: ДНК → Мицелий → P2P.",
    "",
    "## Три уровня",
    "",
    "### 1. ДНК (генотип)",
    "",
    "Файл: `inevionet/evolution/genome.py`",
    "",
    "Каждый узел имеет **геном** — набор из 12+ генов:",
    "",
    "| Ген | Что кодирует | Диапазон |",
    "|-----|--------------|----------|",
    "| speed | скорость передачи | 0.0 - 1.0 |",
    "| reliability | надёжность | 0.0 - 1.0 |",
    "| stealth | скрытность | 0.0 - 1.0 |",
    "| efficiency | эффективность | 0.0 - 1.0 |",
    "| adaptability | адаптивность | 0.0 - 1.0 |",
    "| packet_size | размер пакета | 64 - 9000 |",
    "| ttl | время жизни | 1 - 64 |",
    "| penetration_strategy | метод проникновения | enum |",
    "| masking_channel | канал маскировки | enum |",
    "| industrial_protocol | промышленный протокол | enum |",
    "| stego_method | метод стеганографии | enum |",
    "| use_polymorphic | полиморфизм | bool |",
    "| use_ambient | адаптация к фону | bool |",
    "| use_stego | стеганография | bool |",
    "",
    "### 2. Мицелий (фенотип)",
    "",
    "Файлы: `inevionet/mycelium/*.py`",
    "",
    "- **engine.py** — главный движок",
    "- **penetration.py** — проникновение в сети (6 методов)",
    "- **spores.py** — автономные агенты распространения",
    "- **pheromones.py** — маршрутизация по «феромонам»",
    "",
    "### 3. P2P-сеть (экосистема)",
    "",
    "Сеть состоит из узлов 8 типов:",
    "",
    "| Тип | Цвет | Что это |",
    "|-----|------|---------|",
    "| self | зелёный | твой узел |",
    "| wifi | синий | Wi-Fi сети |",
    "| super | белый | супер-узлы (WiFi + споры) |",
    "| spore | розовый | споры мицелия |",
    "| ble | голубой | Bluetooth LE |",
    "| bluetooth | синий | BT classic |",
    "| cellular | жёлтый | LTE/5G соты |",
    "| industrial | оранжевый | Modbus/MQTT/OPCUA |",
    "| peer | фиолетовый | другие InevioNet-узлы |",
    "",
    "## Поток данных",
    "",
    "```",
    "send() → encrypt → sign → transport →",
    "  ├─ Tor (анонимно)",
    "  ├─ I2P (анонимно, работает в РФ)",
    "  ├─ P2P Bridge (WebRTC)",
    "  ├─ Masking (DPI bypass)",
    "  ├─ Steganography (4 канала)",
    "  └─ Direct (TCP/UDP/DNS/ICMP)",
    "       ↓",
    "receive() → verify signature → decrypt → decode",
    "```",
    "",
    "## Эволюция",
    "",
    "Каждые **4 секунды**:",
    "- Сканер обновляет узлы",
    "- Каждые **40 секунд**: evolve() — новое поколение",
    "- Каждые **50 поколений**: КАТАСТРОФА — сброс diversity",
    "",
    "### Fitness функция",
    "",
    "```",
    "f(g) = speed*0.25 + reliability*0.30 + stealth*0.20",
    "     + efficiency*0.15 + adaptability*0.10",
    "     + size_bonus + ttl_bonus + priority_bonus",
    "```",
    "",
    "### Reward",
    "",
    "Каждая успешная отправка:",
    "- `+0.1` к fitness геномов с той же стратегией",
    "",
    "Каждая неудачная:",
    "- `-0.05` к fitness геномов с той же стратегией",
    "",
    "## Модули",
    "",
    "| Модуль | Файлов | Строк | Назначение |",
    "|--------|--------|-------|------------|",
    "| core | 9 | ~2000 | Ядро: crypto, packet, logger |",
    "| network | 12 | ~5000 | TCP/UDP/DNS/ICMP/HTTP/WS/WebRTC |",
    "| mycelium | 5 | ~1500 | Проникновение, споры, феромоны |",
    "| evolution | 2 | ~800 | Генетический алгоритм |",
    "| masking | 8 | ~3000 | DPI bypass, полиморфизм |",
    "| steganography | 6 | ~1500 | Скрытые каналы |",
    "| industrial | 6 | ~2000 | Modbus/MQTT/OPCUA/DNP3 |",
    "| identity | 8 | ~2000 | Device ID, trust, discovery |",
    "| mesh | 1 | ~500 | Авто-топология |",
    "| symbiotic | 2 | ~800 | Экосистема |",
    "| ai | 2 | ~1000 | Selector + Recursion |",
    "| web | 2 | ~1500 | Flask + UI |",
    "| **ВСЕГО** | **63** | **~22000** | |",
    "",
    "## Ссылки",
    "",
    "- `docs/MODULES.md` — детальное описание модулей",
    "- `docs/MATH.md` — формальная математика",
    "- `README_FOR_DUMMIES.md` — инструкция для пользователя"
)

[System.IO.File]::WriteAllLines((Join-Path $DocsDir "ARCHITECTURE.md"), $arch, [System.Text.UTF8Encoding]::new($false))
Write-Host "[OK] docs\ARCHITECTURE.md" -ForegroundColor Green

# === MODULES.md ===
$modules = @(
    "# InevioNet — Модули",
    "",
    "## core/",
    "",
    "Ядро системы.",
    "",
    "- **crypto.py** — InevioCrypto, KeyPair. AES + RSA подписи",
    "- **packet.py** — GDPPacket. Гарантированная доставка",
    "- **logger.py** — Логирование с ротацией",
    "- **constants.py** — DataPaths, режимы, протоколы",
    "- **exceptions.py** — Кастомные исключения",
    "- **cache.py** — LRU-кэш для KL",
    "- **beacon.py** — Multicast beacons",
    "- **async_utils.py** — Асинхронные хелперы",
    "- **stats_aggregator.py** — Сбор статистики",
    "",
    "## network/",
    "",
    "Сетевые транспорты.",
    "",
    "- **tcp.py** — TCPClient, TCPServer",
    "- **udp.py** — UDPClient, UDPHolePuncher, STUN",
    "- **dns.py** — DNSClient с QNAME/TXT",
    "- **http.py** — HTTPClient с headers injection",
    "- **icmp.py** — ICMPClient с raw socket",
    "- **websocket.py** — WSClient",
    "- **transport.py** — UniversalTransport (все протоколы)",
    "- **rf_scanner.py** — WiFi + BT + BLE + LTE + GPS",
    "- **ble_scanner.py** — BLE через bleak",
    "- **lte_scanner.py** — LTE через netsh mbn",
    "- **cellular_scanner.py** — Оператор + геолокация",
    "- **tor_transport.py** — SOCKS5 через Tor",
    "- **i2p_transport.py** — SAM bridge I2P",
    "- **webrtc_bridge.py** — WebRTC DataChannel",
    "- **bridge_broker.py** — Координатор relay",
    "- **relay_node.py** — Узел-релей",
    "",
    "## mycelium/",
    "",
    "Биомиметическая сеть.",
    "",
    "- **engine.py** — MyceliumEngine",
    "- **penetration.py** — 6 методов проникновения",
    "- **spores.py** — SporeManager, Spore",
    "- **pheromones.py** — PheromoneEngine",
    "",
    "## evolution/",
    "",
    "Генетический алгоритм.",
    "",
    "- **genome.py** — ProtocolGenome, 14 генов",
    "- **engine.py** — EvolutionEngine, catastrophe, reward",
    "",
    "## masking/",
    "",
    "Обход DPI.",
    "",
    "- **masking_engine.py** — Главный движок",
    "- **polymorphic.py** — Разбиение на фрагменты",
    "- **ambient.py** — Адаптация к трафику",
    "- **bayesian.py** — Байесовский выбор канала",
    "- **channel_selector.py** — Селектор каналов",
    "- **firewall_model.py** — Модель firewall",
    "- **detection.py** — KL-дивергенция",
    "- **vulnerability_map.py** — Карта уязвимостей",
    "- **probing.py** — Зондирование",
    "",
    "## steganography/",
    "",
    "Скрытые каналы.",
    "",
    "- **engine.py** — SteganographyEngine",
    "- **dns_tunnel.py** — Данные в DNS",
    "- **http_headers.py** — Данные в headers",
    "- **icmp_payload.py** — Данные в ICMP",
    "- **timing.py** — Данные в таймингах",
    "",
    "## industrial/",
    "",
    "Промышленные протоколы.",
    "",
    "- **base.py** — IndustrialProtocol",
    "- **modbus.py** — ModbusTCP, ModbusRTU",
    "- **mqtt.py** — MQTTClient (paho-mqtt)",
    "- **opcua.py** — OPCUA",
    "- **dnp3.py** — DNP3",
    "",
    "## identity/",
    "",
    "Идентификация.",
    "",
    "- **device_id.py** — DeviceID, DeviceType",
    "- **identity.py** — DeviceIdentity",
    "- **registry.py** — DeviceRegistry",
    "- **discovery.py** — DiscoveryEngine (multicast)",
    "- **trust.py** — TrustEngine",
    "- **presence.py** — PresenceManager",
    "- **fingerprint.py** — DeviceFingerprint",
    "",
    "## Остальные",
    "",
    "- **mesh/auto_topology.py** — Авто-топология",
    "- **symbiotic/ecosystem.py** — Экосистема",
    "- **ai/selector.py** — ProtocolSelector",
    "- **ai/recursion.py** — WeightedRecursion",
    "- **web/app.py** — Flask API (20+ endpoints)",
    "- **web/templates/index.html** — iOS 27 UI",
    "- **orchestrator.py** — Главный класс InevioNet"
)

[System.IO.File]::WriteAllLines((Join-Path $DocsDir "MODULES.md"), $modules, [System.Text.UTF8Encoding]::new($false))
Write-Host "[OK] docs\MODULES.md" -ForegroundColor Green

# === MATH.md ===
$math = @(
    "# InevioNet — Формальная математика",
    "",
    "## 1. Ложный выбор → Мицелий",
    "",
    "**Психология:** «пиво, вино или водка» — иллюзия выбора.",
    "",
    "**Формализация:**",
    "```",
    "A = {a_1, ..., a_n}  — множество альтернатив",
    "f: A → R             — функция исходов",
    "f(a_i) = r           — все ведут к одному",
    "```",
    "",
    "**Ложный выбор:** `|A| > 1` и `|f(A)| = 1`",
    "",
    "**Мицелий:** растёт **во все стороны** → `|f(A)| ≫ 1`",
    "",
    "## 2. Геном как вектор",
    "",
    "```",
    "g = (g_1, ..., g_n) ∈ [0,1]^5 × Z^4 × E^k",
    "```",
    "",
    "где:",
    "- 5 float генов (speed, reliability, stealth, efficiency, adaptability)",
    "- 4 int гена (packet_size, ttl, priority, clone_threshold)",
    "- k enum генов (penetration, masking, industrial, stego)",
    "",
    "## 3. Fitness функция",
    "",
    "```",
    "f(g) = Σ_i w_i · g_i + bonus(g)",
    "```",
    "",
    "где `w = (0.25, 0.30, 0.20, 0.15, 0.10)`",
    "",
    "**Bonus:**",
    "```",
    "size_bonus = max(0, 1 - |packet_size - 1400|/1400) · 0.05",
    "ttl_bonus = min(1, ttl/40) · 0.03",
    "priority_bonus = max(0, 1 - |priority-7|/10) · 0.02",
    "```",
    "",
    "## 4. Эволюция",
    "",
    "**Турнирный отбор:**",
    "```",
    "P_select(g_i) = P(g_i ∈ tournament_size)",
    "winner = argmax_{g ∈ T} f(g)",
    "```",
    "",
    "**Мутация:**",
    "```",
    "g'_i = g_i + N(0, σ²)  с вероятностью p_m",
    "```",
    "",
    "**Кроссовер:**",
    "```",
    "child_i = α·parent1_i + (1-α)·parent2_i + N(0, 0.05)",
    "```",
    "",
    "## 5. Diversity (разнообразие)",
    "",
    "```",
    "D = (1/n) Σ_i σ_i",
    "```",
    "",
    "где σ_i — стандартное отклонение гена i по популяции.",
    "",
    "**Проблема:** D → 0 при сходимости (преждевременная конвергенция).",
    "",
    "**Решение:** КАТАСТРОФА каждые 50 поколений:",
    "```",
    "1. Оставить 70% лучших",
    "2. Инжектировать 30% случайных геномов",
    "3. D растёт обратно",
    "```",
    "",
    "## 6. Reward",
    "",
    "```",
    "f(g, strategy) += +0.1  если success",
    "f(g, strategy) += -0.05 если failure",
    "```",
    "",
    "где `strategy = getattr(g, attr)` для `attr ∈ {penetration, masking, stego, industrial}`",
    "",
    "## 7. Мицелий",
    "",
    "**Апикальный рост:**",
    "```",
    "x_{t+1} = x_t + Δ · (cos θ_t, sin θ_t)",
    "θ_{t+1} = θ_t + N(0, σ²)",
    "```",
    "",
    "**Ветвление:** процесс Гальтона-Ватсона:",
    "```",
    "E[N(t)] = N_0 · μ^t",
    "```",
    "",
    "**Анастомозы:** цикломатическая сложность:",
    "```",
    "C = E - V + 1",
    "```",
    "",
    "## 8. Феромоны",
    "",
    "**Испарение:**",
    "```",
    "s(t) = s_0 · exp(-λ · t / 60)",
    "```",
    "",
    "**Усиление:**",
    "```",
    "s ← min(1, s + 0.1)",
    "```",
    "",
    "**Оценка:**",
    "```",
    "score = strength · success_rate",
    "```",
    "",
    "## 9. Споры",
    "",
    "**Жизнеспособность:**",
    "```",
    "v(t) = v_0 - 0.05 · t",
    "```",
    "",
    "**Условие выживания:**",
    "```",
    "N_s · p > 1",
    "```",
    "",
    "где N_s — число спор, p — вероятность прорастания.",
    "",
    "## 10. Маскировка",
    "",
    "**KL-дивергенция:**",
    "```",
    "D_KL(P || Q) = Σ P(i) · log(P(i) / Q(i))",
    "```",
    "",
    "**Байесовский выбор:**",
    "```",
    "P(channel) = α / (α + β)",
    "```",
    "",
    "где α, β — параметры Beta-распределения.",
    "",
    "## 11. P2P Bridge",
    "",
    "**Broker:**",
    "```",
    "relay* = argmin_{r ∈ Relays} load_ratio(r)",
    "load_ratio(r) = current_load(r) / capacity(r)",
    "```",
    "",
    "**WebRTC:**",
    "```",
    "Offer: SDP_A → Broker → SDP_B (Answer)",
    "DataChannel: шифрование DTLS + SRTP",
    "```",
    "",
    "## 12. Формула проекта",
    "",
    "```",
    "G(t+1) = Рост(G(t), μ*, D*)  при s* = argmax f(s)",
    "```",
    "",
    "где:",
    "- G(t) — топология сети в момент t",
    "- μ* — оптимальное ветвление",
    "- D* — оптимальная диффузия",
    "- s* — эволюционно стабильная стратегия",
    "",
    "## 13. Итог",
    "",
    "InevioNet = ДНК (геном) + Мицелий (сеть) + P2P (экосистема)",
    "",
    "Все три уровня подчиняются **законам эволюции**:",
    "- Мутация + отбор = адаптация",
    "- Катастрофа = punctuated equilibrium",
    "- Diversity = гарантия выживания"
)

[System.IO.File]::WriteAllLines((Join-Path $DocsDir "MATH.md"), $math, [System.Text.UTF8Encoding]::new($false))
Write-Host "[OK] docs\MATH.md" -ForegroundColor Green

Write-Host ""
Write-Host "=== DOCS CREATED ===" -ForegroundColor Cyan
Get-ChildItem $DocsDir | ForEach-Object {
    Write-Host "  $($_.Name) ($([math]::Round($_.Length/1KB, 1)) KB)" -ForegroundColor White
}